version: 2.1
orbs:
  python: circleci/python@1.2

workflows:
  sample:
    jobs:
      - build-and-test
jobs:

  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            pip install -r requirements.txt
            cp -f .circleci/resources/pytest_build_config.ini pytest.ini
            shopt -s globstar
            #TESTFILES=$(circleci tests glob tests/**/test*.py | circleci tests split --split-by=timings)
            #echo $TESTFILES
            mkdir -p test-results
            shopt -u globstar
            #python -m pytest --junitxml=test-results/junit.xml $TESTFILES
            pytest -v --junitxml="test-results/junit.xml" test_api.py test_api2.py test_api3.py test_api4.py

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
